version: '3.8'

services:
  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql-certificados-dev
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - mysql_data:/bitnami/mysql
    networks:
      - dev-net
  
volumes:
  mysql_data:

networks:
  dev-net:
